version: '3.8'

services:
  similaryti_parsing:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    env_file:
      - .env
    image: questions-api